---
title: "Supply Chain"
author: "Deeksha Gupta"
date: "2/9/2020"
output: pdf_document
---

```{r setup, include=FALSE}
train <- read.csv("D:/UIC SEM 2/Supply Chain/Case Study/Supply Chain/train.csv")
test <- read.csv("D:/UIC SEM 2/Supply Chain/Case Study/Supply Chain/test.csv")
```



```{r cars}
library(forecast) #load forecast library

###########Extract time series and plot#########
dataFreq= 52 #Data frequency of time series. Set to 12 and 4 for monthly and quaterly data, respectively
startEntry= c(2010,2) #Time stamp of first entry in time series e.g. c(2010,2) implies second quarter of 2012 if data frequency equals 4
demandTS <- ts(train, frequency=dataFreq,
               start=startEntry) #create a time series

plot(demandTS,main = "Sales of Walmart store1 dept1",
     xlab="Year.week",ylab="Sales") #plot time series.
###########Decompose time series and plot#########
```

```{r cars}
#Decompose methods return an object containing
tsDecomp <- decompose(demandTS) #classical decomposition. Can be set to multiplicative or additive
#plot(tsDecomp) #plot decomposed time series

###########Prepare time series for forecasting#########
###We partition the time series into a training set for
###forecasting and a test set to evaluate accuracy
#trainSetStart= c(2010,5) #training set start location in time series (typically the first entry)
#trainSetEnd= c(2012,4) #training set end location in time series (typically covers 70% of time series)
#testSetStart= c(2012,5) #test set start location in time series (typically location of entry after training set ends)
#testSetEnd= c(2012,52) #test set end location in time series (typically end of time series)

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
############To acheive Stationery#################
library(fUnitRoots)
urkpssTest(demandTS, type = c("tau"), lags = c("short"),use.lag = NULL, doplot = TRUE)
tsstationary = diff(demandTS, differences=1)
plot(tsstationary, main = "After removing non stationarity")

###########Calculate Autocorrelation##############
acf(demandTS,lag.max=34)

###########Removing Seasonality#################
timeseriesseasonallyadjusted <- demandTS- tsDecomp$seasonal
tsseasonality <- diff(timeseriesseasonallyadjusted, differences=1)
plot(tsseasonality, main="Removing Seasonality and making data Stationary")
par(mfrow=c(2,1))
acf(tsseasonality, lag.max=34) 
pacf(tsseasonality, lag.max=34)


```



```{r pressure, echo=FALSE}

###########Fitiitng the model###########
#acf(diff(log(demandTS)))
#pacf(diff(log(demandTS)))
tsDataSales<-ts(train$Weekly_Sales,start=c(2010),end=c(2012.5),frequency=52)
fit <- arima(log(tsDataSales), c(0, 1, 1), seasonal = list(order = c(0, 1, 1), period = 52)) 
pred <- predict(fit, n.ahead = 52)
pred
ts.plot(tsDataSales,2.718^pred$pred, log = "y", lty = c(1,3),main = "Forecasts of Stores") 

```





